// <auto-generated />
using BugDB.BL;
using BugDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BugDB.Data.Migrations
{
    [DbContext(typeof(BugDBContext))]
    [Migration("20180217135742_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BugDB.BL.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<int?>("ClientId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("TblAddress");
                });

            modelBuilder.Entity("BugDB.BL.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContactName");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("TblClient");
                });

            modelBuilder.Entity("BugDB.BL.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.HasKey("Id");

                    b.ToTable("TblEmail");
                });

            modelBuilder.Entity("BugDB.BL.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClientId");

                    b.Property<int>("ProjectFormat");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("TblProject");
                });

            modelBuilder.Entity("BugDB.BL.Replicator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AddressId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("TblReplicator");
                });

            modelBuilder.Entity("BugDB.BL.Address", b =>
                {
                    b.HasOne("BugDB.BL.Client")
                        .WithMany("AddressList")
                        .HasForeignKey("ClientId");
                });

            modelBuilder.Entity("BugDB.BL.Replicator", b =>
                {
                    b.HasOne("BugDB.BL.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");
                });
#pragma warning restore 612, 618
        }
    }
}
